pipeline{
    agent any
        stages{
            stage("Cloning Repo from GITHUB"){
                steps{
                    git branch: 'main', changelog: false, poll: false, url: 'https://github.com/sankararaorajamandri/withCrednetials-1.git'
                }
            }
            stage("Build"){
                steps{
                    dir('3-java-jenkins-docker-app') {
                        sh ' mvn clean package'
                    }
                }
            }
            stage("Test"){
                steps{
                    dir('3-java-jenkins-docker-app'){
                        sh 'mvn test'
                    }
                }
            }
            stage("Compile"){
                steps{
                    dir('3-java-jenkins-docker-app'){
                        sh 'mvn compile'
                    }
                }
            }
            stage("RUNTIME"){
                steps{
                    sh 'java -jar ./3-java-jenkins-docker-app/target/java-jenkins-docker-1.0-SNAPSHOT.jar'
                }
            }
            stage("Docker Image"){
                steps{
                    dir('3-java-jenkins-docker-app'){
                       sh 'docker build -t java-jenkins-docker:latest .' 
                    }
                }
            }
            stage('Docker image Tag') {
                steps {
                    dir('3-java-jenkins-docker-app') {
                    sh 'docker tag java-jenkins-docker:latest shankar2645/java-jenkins-docker:1.0'
                    }
                }
            }
    }
    
}
